.yarnrc, Jenkinsfile, example/browser-app/package.json, example/coffee-theia/package.json, example/coffee-theia/src/node/backend-module.ts, example/dev-example/package.json, example/dev-example/src/browser/api-test-menu.ts, example/electron-app/package.json, lerna.json, modelserver-theia/package.json, package.json, tsconfig.json, yarn.lock
- Bump our package versions to 0.7.0, bump Theia version to next
- Mark example packages private and only publish 'modelserver-theia'
- Skip building of electron app as it needs X11 (not avail on Jenkins)
- Provide Jenkinsfile for build and deployment of modelserver-theia
- Fix repository and homepage links
=> Fixes #9: Setup CI for build/deploy, fix package versions and bump Theia

modelserver-theia/README.md
The link was pointing to the old repository.
=> Fix repository link in modelserver package's README

example/dev-example/src/browser/api-test-menu.ts, modelserver-theia/src/common/model-server-client.ts, modelserver-theia/src/node/modelserver-api.ts, modelserver-theia/src/node/rest-client.ts
- Add missing method for listing model uris: getModelUris
-- Add to example API test menu
- Ensure getAll returns a list of model
-- Introduce dedicated model type with modelUri and content properties
- Clean up code and use more types
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
=> Fixes #19, Fixes #20: Align client API with protocol

example/dev-example/src/browser/api-test-menu.ts, modelserver-theia/src/browser/model-server-frontend-client.ts, modelserver-theia/src/common/model-server-client.ts, modelserver-theia/src/node/modelserver-api.ts
- Structure ModelServer test menu for better overview
- Add all possible subsription scenarios to ModelServer test menu
- Subscribe without explicit timeout
- Session does not time out and is open until explicitly closed via unsubscribe.
- Subscribe with timeout 60s and keep alive messages
- Session is opened with a timeout of 60s and client sends keep alive messages to keep session opened every 59s until excplicitly closed via unsubscribe.
- Subscribe with timeout 10s
- Session is opened with a timeout of 10s and is closed if idle timeout is reached; user may send keep alive messages manually and unsubscribe within the defined timeout.
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
=> Prolong WebSocket connections via timeout and keepAlive messages

example/dev-example/src/browser/api-test-menu.ts, modelserver-theia/src/browser/model-server-subscription-client.ts, modelserver-theia/src/common/model-server-api.ts, modelserver-theia/src/common/model-server-paths.ts, modelserver-theia/src/node/model-server-client.ts
Adds examples for the functionalities introduced in [this PR](https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/43/)
Signed-off-by: Simon Graband <simon.graband@tum.de>
=> Add validation endpoint examples

example/dev-example/src/browser/api-test-menu.ts, example/dev-example/src/common/dev-model-server-client.ts, modelserver-theia/README.md, modelserver-theia/src/common/base-model.ts, modelserver-theia/src/common/change-model.ts, modelserver-theia/src/common/command-model.ts, modelserver-theia/src/common/index.ts, modelserver-theia/src/common/model-server-api.ts, modelserver-theia/src/common/model-server-util.ts, modelserver-theia/src/node/model-server-client.ts
- Provide classes instead of interfaces for model server commands
- Provide type guards for classes to evaluate data from server
- Add types for CommandExecutionResult and related classes
Part of emfcloud-modelserver/issues/87
- Adapt command URI to updated URI
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
=> Fixes #38: Provide more utility methods for commands

modelserver-theia/src/common/change-model.ts
Fixing incorrect EClasses which prevent from using the ChangeModel and its 'is' methods.
=> Fixes eclipse-emfcloud#55: Incorrect ChangeModel

modelserver-markers-theia/src/browser/diagnostic-adapter.ts
In newer version of the vscode-languageserver-types package numbers are replaced with integer, uinteger or decimal so '-1' no longer fulfills the Position.is-check.
Previously negative position line and character numbers defaulted to 0 anyway.
see https://github.com/microsoft/vscode-languageserver-node/blame/d58c00bbf8837b9fd0144924db5e7b1c543d839e/types/src/main.ts#L95
=> Fixes #67: Use unsigned integer for position start and end

packages/modelserver-client/src/model-server-client-v2.spec.ts, packages/modelserver-client/src/model-server-client-v2.ts
v2 API specifies `PUT` on /models endpoint, not `PATCH`,  to perform a full model update.
=> #150 Use PUT request for full model update

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
The issue templates for bugs and feature requests automatically apply the `modelserver` label to new issues.
=> #80 Add issue templates to the repository

packages/modelserver-client/src/utils/patch-utils.ts
The PR completes the definition of type guard utility functions for the JSON Patch operations supported by the Model Server API:
- add missing override signature for the custom type guard in the `isReplace(...)` function
- add missing guard operations for `add` operation
- for completeness (not strictly necessary) add  a guard operation for `remove` operation
=> Round out the operation type guards

.vscode/launch.json, packages/modelserver-client/package.json, packages/modelserver-client/src/index.ts, packages/modelserver-client/src/model-server-client-api-v2.ts, packages/modelserver-client/src/model-server-client-v2-integration.spec.ts, packages/modelserver-client/src/model-server-client-v2.spec.ts, packages/modelserver-client/src/model-server-client-v2.ts, packages/modelserver-client/src/model-server-message.ts, packages/modelserver-client/src/model-server-notification.ts, packages/modelserver-client/src/model/base-model.ts, packages/modelserver-client/src/model/diagnostic.spec.ts, packages/modelserver-client/src/model/diagnostic.ts, packages/modelserver-client/src/subscription-listener.ts, packages/modelserver-client/src/utils/patch-utils.ts, packages/modelserver-client/src/utils/type-util.spec.ts, packages/modelserver-client/src/utils/type-util.ts, packages/modelserver-theia/src/browser/frontend-module.ts, packages/modelserver-theia/src/browser/model-server-subscription-client.ts, yarn.lock
Note: the PR is based on the standalone client PR #69 
This is the client changes to support the V2 ModelServer API. The changes are described on the corresponding Model Server pull request: eclipse-emfcloud/emfcloud-modelserver/pull/151
=> #150 Provide Client API V2 and Client implementation

packages/modelserver-client/src/utils/type-util.spec.ts, packages/modelserver-client/src/utils/type-util.ts
Skip over all primitive and primitive-like values, including null
which actually is an object, in the traversal of JSON documents.
Also add coverage of empty objects and empty arrays to the
tests to ensure that they are faithfully copied.
=> Fix #85: Exception on JSON containing null

packages/modelserver-client/src/model-server-client-api-v2.ts, packages/modelserver-theia/src/browser/frontend-module.ts, packages/modelserver-theia/src/common/protocol.ts, packages/modelserver-theia/src/node/backend-module.ts, packages/modelserver-theia/src/node/index.ts, packages/modelserver-theia/src/node/launch-options.ts, packages/modelserver-theia/src/node/model-server-backend-contribution.ts, packages/modelserver-theia/src/node/theia-model-server-client-v2.ts, packages/modelserver-theia/src/node/theia-model-server-client.ts
Add a variant of the Theia-integrated services for _Model Server_ API v2, including:
- `TheiaModelServerClientV2` implementing the RPC service for `ModelServerClientApiV2` on a service path that is distinct from the original `TheiaModelServerClient`
- new subscription option for API v2 to select the JSON Patch `path` scheme in incremental update notifications
- new launch options for the `modelserver-node` process
- new backend server launcher implementation that is bound dynamically when the options include the modelserver-node. This actually fixes at least a part of eclipse-emfcloud/modelserver-node#20
The new `TheiaBackendModelServerClientV2` implementation accounts for the cancellation token replacing optional arguments that the remote caller omits. The same is done retroactively in …
=> Model Server API v2 in Theia services

packages/modelserver-theia/src/node/launch-options.ts, packages/modelserver-theia/src/node/model-server-backend-contribution.ts
Implement the suggested extensibility hooks for subclasses to selectively override Java server and/or Node server launching. Also, because it's a related subject, fix the port assignment for the Java server in the two-server scenario allowing for subclasses also to override that.
Fixes #101.
Fixes #100.
=> #101 Model Server Launcher extensibility

packages/modelserver-client/src/model-server-client-v2.spec.ts, packages/modelserver-client/src/model-server-client-v2.ts, packages/modelserver-client/src/model-server-client.spec.ts, packages/modelserver-client/src/model-server-client.ts
The baseUrl did not handle trailing slashes correctly.
The V2 Client expected the baseUrl to not have a trailing slash.
The V1 Client expected the baseUrl to have a trailing slash.
With the fix the trailing slash is always removed and added during the
calculation of the subscription path.
Fixes #99
=> Fix baseUrl handling

packages/modelserver-client/src/model-server-client-api-v2.ts, packages/modelserver-client/src/model-server-client-v2-integration.spec.ts, packages/modelserver-client/src/model-server-client-v2.ts, packages/modelserver-client/src/model-server-message.ts
Update the model-server-client V2 to handle additional patches returned by the server during edit, undo and redo requests: https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/215
refs https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/209
=> 209: API V2: Return patches for each affected resource

packages/modelserver-client/src/model-server-client-api-v2.ts, packages/modelserver-client/src/model-server-client-v2-integration.spec.ts, packages/modelserver-client/src/model-server-client-v2.ts, packages/modelserver-theia/src/node/theia-model-server-client-v2.ts
- Add the possibility to specify Json Patches via a list of "Model Patch" objects, referencing a modelUri and a Patch. This allows edition of multi-resource models, with one Json Patch per resource.
Additional minor fixes:
- Fix a minor warning in the integration tests
- Support the optional "format" attribute in the client V2 implementation
Signed-off-by: Camille Letavernier <cletavernier@eclipsesource.com>
=> 159: API V2: Properly define and support multi-resources patches/operations

Jenkinsfile, packages/modelserver-client/package.json, yarn.lock
- update yarn.lock
- pin @types/moxios to 0.4.14
0.4.15 changes the version dependency from ^0.24.0 to >=0.13.0
and thus pulls in the latest version of axios (as of 2022-06-22
beeing 0.27.2)  which  is incompatible by type with the moxios types.
Thus pinning the version to 0.4.14 allows for a minimal change, which
is also compatible with our axios dependency.
=> Update yarn.lock to build against the latest

examples/coffee-theia/config/log4j2.xml, examples/coffee-theia/src/node/backend-module.ts, package.json, yarn.lock
- Add custom log4j2.xml configuration for coffee-theia example application if modelserver is started from JAR
- Update ts-node dependency to fix download script
Part of eclipse-emfcloud/emfcloud-modelserver#187
Based on [emfcloud-modelserver PR #229](https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/229)
**How to test**
- Use the packaged jar of the modelserver (from PR #229) and copy to `examples/coffee-theia/build` (instead of the downloaded modelserver jar).
- The provided log configuration only logs errors to the backend console, all other content should be logged to the (rolling) log file, which can be found in `examples/browser-app/logs`.
=> #187 Use custom log4j2 logging configuration

packages/modelserver-theia/src/node/theia-model-server-client-v2.ts
Ensure ModelServerCommand prototype is explicitly set if pure commands are used (which applies to using custom commands)
Resolves #115
=> #115 Ensure ModelServerCommand prototype is set

packages/modelserver-client/src/model/command-model.ts, packages/modelserver-client/src/utils/model-server-utils.ts
Let user build a "SetCommand" with model objects for containment ref. This SetCommand must be correctly interpreted by server.
Signed-off-by: vhemery <vincent.hemery@bonitasoft.com>
Should be merged after https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/258
=> Allow to set a mono containment reference (#52)

packages/modelserver-client/src/model-server-client-api-v1.ts, packages/modelserver-client/src/model-server-client-v2.spec.ts, packages/modelserver-client/src/model-server-client-v2.ts, packages/modelserver-client/src/model-server-client.spec.ts, packages/modelserver-client/src/model-server-client.ts, packages/modelserver-theia/src/browser/model-server-frontend-contribution.ts, packages/modelserver-theia/src/common/jsonrpc-proxy-factory.ts
- Ensure workspace configurations are URIs
- Remove file uri manipulation of workspace configurations
- Update TheiaModelServerJsonRpcProxyFactory to properly forward arguments that are URI arrays or objects that hold URI values (such as the workspace configuration object)
- Update tests
Contributed on behalf of STMicroelectronics
Part of https://github.com/eclipse-emfcloud/emfcloud/issues/179
=> #179 Use URIs in workspace configuration

examples/dev-example/src/browser/api-test-menu.ts, packages/modelserver-client/src/utils/index.ts, packages/modelserver-client/src/utils/uri-utils.ts, packages/modelserver-markers-theia/README.md, packages/modelserver-markers-theia/src/browser/diagnostic-manager.ts, packages/modelserver-theia/src/browser/frontend-module.ts, packages/modelserver-theia/src/node/backend-module.ts
- Ensure URIs are used in DiagnosticManager and convert to TheiaURI if handing over to the problemManager
- Provide basic URIUtil functions for conversion to/from TheiaURIs
- Export TheiaModelServerJsonRpcProxyFactory properly from the containing common package
Contributed on behalf of STMicroelectronics
Part of https://github.com/eclipse-emfcloud/emfcloud/issues/179
=> #179 Use URIs in DiagnosticManager

lerna.json, package.json, yarn.lock
Update lerna to ^6.0.0 as the old version
breaks builds with Python 3.11.
Contributed on behalf of STMicroelectronics
=> Update lerna to ^6.0.0

packages/modelserver-theia/src/common/jsonrpc-proxy-factory.ts
We have to first check for an array and only then for an object as every array is also an object.
=> Fix order in which args are checked in the proxy factory

examples/browser-app/package.json, examples/coffee-theia/package.json, examples/dev-example/package.json, packages/modelserver-markers-theia/package.json, packages/modelserver-theia/package.json, yarn.lock
Part of https://github.com/eclipse-emfcloud/emfcloud/issues/194
Contributed on behalf of STMicroelectronics
=> #194 Switch to peer dependencies for `@theia` dependencies

.eslintrc.js, Jenkinsfile, configs/errors.eslintrc.json, packages/modelserver-client/package.json, packages/modelserver-client/src/model-server-client-v2.ts, packages/modelserver-client/src/model-server-client.ts, packages/modelserver-theia/package.json, yarn.lock
- Follow-up of #135: Align duplicate `ws` dependency version
- Update eslint config to use dynamic year in headers
- Re-generate yarn.lock to update several dependencies and resolve several dependabot alerts
- Remove obsolete custom isAxiosError check and reuse built-in type check
- Due to CI problems after Theia update: Increase pod resource limits
=> #197 Follow up and housekeeping

packages/modelserver-client/package.json, packages/modelserver-theia/package.json, yarn.lock
- Align the `ws` dependency version with Theia's version `^7.1.2`
- The newer version (>8) seems to have breaking changes regarding the `MessageEvent`. This could not be serialized anymore `onMessage` notifications
- See also https://github.com/websockets/ws/releases/tag/8.0.0
Follow-up of #136
=> #194 Align ws dependency version with @theia/core
